# Docker Compose para desarrollo del frontend únicamente
# Uso: docker-compose -f docker-compose.frontend.yml up

version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-/api}
        VITE_API_AUTH_BASE_URL: ${VITE_API_AUTH_BASE_URL:-/auth}
        VITE_APP_ENV: ${VITE_APP_ENV:-production}
    container_name: bike-frontend-only
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Redes
networks:
  default:
    name: bike_network
    external: true
