# Etapa 1: Build
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
# Instalar dependencias de producción y desarrollo
RUN npm install

RUN npm install terser --save-dev


COPY . .

RUN npm run build

# Etapa 2: Servidor web
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

# Configuración de Nginx personalizada
#COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
# Iniciar Nginx en primer plano
CMD ["nginx", "-g", "daemon off;"]
